//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Chess.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ChessParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IChessVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ChessParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParse([NotNull] ChessParser.ParseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ChessParser.move"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMove([NotNull] ChessParser.MoveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ChessParser.standardMove"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStandardMove([NotNull] ChessParser.StandardMoveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ChessParser.piece"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPiece([NotNull] ChessParser.PieceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ChessParser.disambiguation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDisambiguation([NotNull] ChessParser.DisambiguationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ChessParser.capture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCapture([NotNull] ChessParser.CaptureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ChessParser.square"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSquare([NotNull] ChessParser.SquareContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ChessParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] ChessParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ChessParser.rank"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRank([NotNull] ChessParser.RankContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ChessParser.promotion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPromotion([NotNull] ChessParser.PromotionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ChessParser.checkOrMate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCheckOrMate([NotNull] ChessParser.CheckOrMateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ChessParser.castling"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastling([NotNull] ChessParser.CastlingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ChessParser.enPassant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnPassant([NotNull] ChessParser.EnPassantContext context);
}
